/**
 * UK curriculum content for Rawson Learning Lab
 * Aligned to National Curriculum KS2/KS3 foundations → GCSE pathway
 * Bella-Rose (12) · George (10)
 */

const LEARNERS = {
  bella: {
    id: "bella",
    name: "Bella-Rose",
    fullName: "Bella-Rose Rawson",
    age: 12,
    yearGroup: "Year 7–8",
    stage: "ks3",
    emoji: "🌸",
    theme: "bella",
    tagline: "Personalised KS3 path toward GCSE",
  },
  george: {
    id: "george",
    name: "George",
    fullName: "George Rawson",
    age: 10,
    yearGroup: "Year 5–6",
    stage: "ks2",
    emoji: "🍃",
    theme: "george",
    tagline: "Personalised KS2 path toward GCSE",
  },
};

const SUBJECTS = {
  maths: {
    id: "maths",
    name: "Maths",
    emoji: "🔢",
    colour: "maths",
    illust: "assets/illust/subject-maths.jpg",
    illustAlt: "Friendly fox teaching maths with numbers and pizza fractions",
  },
  english: {
    id: "english",
    name: "English",
    emoji: "📚",
    colour: "english",
    illust: "assets/illust/subject-english.jpg",
    illustAlt: "Friendly rabbit reading a magical book in the garden",
  },
  science: {
    id: "science",
    name: "Science",
    emoji: "🔬",
    colour: "science",
    illust: "assets/illust/subject-science.jpg",
    illustAlt: "Hedgehog scientist in a garden greenhouse lab",
  },
};

/** Fun Grok Imagine storybook art used across the site */
const ILLUST = {
  mascot: {
    src: "assets/illust/mascot-owl.jpg",
    alt: "Owl tutor in a garden classroom shed",
  },
  pathway: {
    src: "assets/illust/pathway-climb.jpg",
    alt: "Garden path climbing to a golden star trophy",
  },
  celebrate: {
    src: "assets/illust/celebrate.jpg",
    alt: "Garden friends celebrating with confetti and stars",
  },
  exam: {
    src: "assets/illust/exam-workout.jpg",
    alt: "Brave owl ready for an exam workout",
  },
  teach: {
    src: "assets/illust/teach-lesson.jpg",
    alt: "Owl tutor teaching a fox student in the garden",
  },
  unlock: {
    src: "assets/illust/unlock-stage.jpg",
    alt: "Magical garden door unlocking the next stage",
  },
  pick: {
    src: "assets/illust/pick-learners.jpg",
    alt: "Garden friends ready for a day of learning",
  },
};

/** Skill definitions used for diagnostics + adaptive courses */
const SKILLS = {
  maths: {
    number: { name: "Number & place value", gcse: "Number" },
    operations: { name: "Four operations", gcse: "Number" },
    fractions: { name: "Fractions, decimals & %", gcse: "Ratio & proportion" },
    algebra: { name: "Algebra thinking", gcse: "Algebra" },
    geometry: { name: "Shape & measure", gcse: "Geometry" },
    data: { name: "Data & probability", gcse: "Statistics" },
  },
  english: {
    grammar: { name: "Grammar & sentences", gcse: "Writing AO6" },
    punctuation: { name: "Punctuation & spelling", gcse: "Writing AO6" },
    vocabulary: { name: "Vocabulary & meaning", gcse: "Reading AO2" },
    reading: { name: "Reading comprehension", gcse: "Reading AO1–AO4" },
    writing: { name: "Writing craft", gcse: "Writing AO5" },
  },
  science: {
    biology: { name: "Biology (living things)", gcse: "Biology" },
    chemistry: { name: "Chemistry (materials)", gcse: "Chemistry" },
    physics: { name: "Physics (forces & energy)", gcse: "Physics" },
    method: { name: "Working scientifically", gcse: "Working scientifically" },
  },
};

/**
 * Diagnostic questions.
 * stage: "ks2" | "ks3" | "both"
 * answer: index for multi, string for typed (normalised)
 */
const DIAGNOSTICS = {
  maths: [
    {
      id: "m1",
      skill: "number",
      stage: "both",
      q: "What is the value of the digit 7 in 47,205?",
      type: "multi",
      options: ["7", "70", "700", "7,000"],
      answer: 3,
      explain: "In 47,205 the 7 is in the thousands place → 7,000.",
    },
    {
      id: "m2",
      skill: "operations",
      stage: "both",
      q: "Calculate 48 × 6.",
      type: "typed",
      answer: "288",
      explain: "48 × 6 = (50 × 6) − (2 × 6) = 300 − 12 = 288.",
    },
    {
      id: "m3",
      skill: "operations",
      stage: "both",
      q: "What is 1,000 − 367?",
      type: "typed",
      answer: "633",
      explain: "1,000 − 367 = 633.",
    },
    {
      id: "m4",
      skill: "fractions",
      stage: "both",
      q: "Which fraction is equivalent to ½?",
      type: "multi",
      options: ["2/6", "3/6", "4/6", "5/8"],
      answer: 1,
      explain: "3/6 simplifies to 1/2.",
    },
    {
      id: "m5",
      skill: "fractions",
      stage: "both",
      q: "What is 25% of 80?",
      type: "typed",
      answer: "20",
      explain: "25% = ¼, and 80 ÷ 4 = 20.",
    },
    {
      id: "m6",
      skill: "fractions",
      stage: "ks3",
      q: "Write 0.35 as a fraction in its simplest form.",
      type: "multi",
      options: ["35/100", "7/20", "3/5", "35/10"],
      answer: 1,
      explain: "0.35 = 35/100 = 7/20.",
    },
    {
      id: "m7",
      skill: "algebra",
      stage: "ks2",
      q: "If △ + 9 = 20, what is △?",
      type: "typed",
      answer: "11",
      explain: "△ = 20 − 9 = 11.",
    },
    {
      id: "m8",
      skill: "algebra",
      stage: "ks3",
      q: "Simplify: 3a + 5a − 2a",
      type: "multi",
      options: ["6a", "10a", "6", "3a"],
      answer: 0,
      explain: "3 + 5 − 2 = 6, so 6a.",
    },
    {
      id: "m9",
      skill: "algebra",
      stage: "ks3",
      q: "Solve: 2x + 4 = 18",
      type: "typed",
      answer: "7",
      explain: "2x = 14, so x = 7.",
    },
    {
      id: "m10",
      skill: "geometry",
      stage: "both",
      q: "A triangle has angles 50° and 60°. What is the third angle?",
      type: "typed",
      answer: "70",
      explain: "Angles in a triangle sum to 180°. 180 − 50 − 60 = 70°.",
    },
    {
      id: "m11",
      skill: "geometry",
      stage: "both",
      q: "Perimeter of a rectangle 8 cm by 5 cm?",
      type: "multi",
      options: ["13 cm", "26 cm", "40 cm", "20 cm"],
      answer: 1,
      explain: "2 × (8 + 5) = 26 cm.",
    },
    {
      id: "m12",
      skill: "data",
      stage: "both",
      q: "The mean of 4, 6, 10 is…",
      type: "typed",
      answer: "about 6.67 or 20/3",
      accept: ["6.67", "6.7", "20/3", "6.666", "6⅔", "6 2/3", "6.66"],
      explain: "Mean = (4+6+10) ÷ 3 = 20 ÷ 3 ≈ 6.67.",
    },
    {
      id: "m13",
      skill: "data",
      stage: "ks3",
      q: "A fair coin is flipped. Probability of heads?",
      type: "multi",
      options: ["0", "1/4", "1/2", "1"],
      answer: 2,
      explain: "Two equally likely outcomes → 1/2.",
    },
  ],
  english: [
    {
      id: "e1",
      skill: "grammar",
      stage: "both",
      q: "Which sentence is grammatically correct?",
      type: "multi",
      options: [
        "They was going to the park.",
        "They were going to the park.",
        "They is going to the park.",
        "They be going to the park.",
      ],
      answer: 1,
      explain: "Plural subject 'they' takes 'were'.",
    },
    {
      id: "e2",
      skill: "grammar",
      stage: "both",
      q: "Identify the verb in: 'The cat slept on the mat.'",
      type: "multi",
      options: ["cat", "slept", "on", "mat"],
      answer: 1,
      explain: "'Slept' is the action word (verb).",
    },
    {
      id: "e3",
      skill: "punctuation",
      stage: "both",
      q: "Where should the apostrophe go? The dogs bone was buried.",
      type: "multi",
      options: ["dogs'", "dog's", "dogs", "dog's'"],
      answer: 1,
      explain: "One dog owns the bone → dog's.",
    },
    {
      id: "e4",
      skill: "punctuation",
      stage: "both",
      q: "Which is spelled correctly?",
      type: "multi",
      options: ["definately", "definitely", "definatly", "definetely"],
      answer: 1,
      explain: "definitely — think 'finite' in the middle.",
    },
    {
      id: "e5",
      skill: "vocabulary",
      stage: "both",
      q: "What does 'rapid' mean?",
      type: "multi",
      options: ["slow and careful", "fast", "heavy", "noisy"],
      answer: 1,
      explain: "Rapid means quick or fast.",
    },
    {
      id: "e6",
      skill: "vocabulary",
      stage: "ks3",
      q: "Which word is a synonym of 'brave'?",
      type: "multi",
      options: ["cowardly", "fearful", "courageous", "timid"],
      answer: 2,
      explain: "Courageous means brave.",
    },
    {
      id: "e7",
      skill: "reading",
      stage: "both",
      passage:
        "Maya stared at the storm clouds. The wind tugged her coat. She had promised to deliver the letter before nightfall, even if the sky fell.",
      q: "What can you infer about Maya?",
      type: "multi",
      options: [
        "She is lazy",
        "She is determined to keep her promise",
        "She loves storms",
        "She forgot the letter",
      ],
      answer: 1,
      explain: "She continues despite the storm because she promised.",
    },
    {
      id: "e8",
      skill: "reading",
      stage: "both",
      passage:
        "The library was silent except for the soft tick of a clock. Dust floated in a shaft of light. Tom turned a page carefully, as if the book might break.",
      q: "Which word best describes the atmosphere?",
      type: "multi",
      options: ["chaotic", "peaceful / quiet", "angry", "sporty"],
      answer: 1,
      explain: "Silence, soft ticking and careful movement create a calm mood.",
    },
    {
      id: "e9",
      skill: "writing",
      stage: "both",
      q: "Which sentence uses a simile?",
      type: "multi",
      options: [
        "The moon was bright.",
        "The moon was like a silver coin.",
        "The moon glowed.",
        "The moon, high above, watched.",
      ],
      answer: 1,
      explain: "A simile compares using 'like' or 'as'.",
    },
    {
      id: "e10",
      skill: "writing",
      stage: "ks3",
      q: "Which is the best topic sentence for a paragraph about recycling?",
      type: "multi",
      options: [
        "I like pizza.",
        "Recycling helps protect the environment in several important ways.",
        "Then we put bottles in a box.",
        "The end.",
      ],
      answer: 1,
      explain: "A topic sentence introduces the main idea of the paragraph.",
    },
    {
      id: "e11",
      skill: "grammar",
      stage: "ks3",
      q: "Which is a complex sentence?",
      type: "multi",
      options: [
        "She ran.",
        "She ran and she jumped.",
        "Although it rained, she ran.",
        "Run!",
      ],
      answer: 2,
      explain: "A complex sentence has a main clause + subordinate clause (Although…).",
    },
  ],
  science: [
    {
      id: "s1",
      skill: "biology",
      stage: "both",
      q: "Which organ pumps blood around the body?",
      type: "multi",
      options: ["Lungs", "Brain", "Heart", "Stomach"],
      answer: 2,
      explain: "The heart is a muscular pump.",
    },
    {
      id: "s2",
      skill: "biology",
      stage: "both",
      q: "Plants make food using sunlight in a process called…",
      type: "multi",
      options: ["respiration", "photosynthesis", "digestion", "evaporation"],
      answer: 1,
      explain: "Photosynthesis uses light, water and CO₂ to make glucose.",
    },
    {
      id: "s3",
      skill: "biology",
      stage: "ks3",
      q: "Where does most digestion of food begin in humans?",
      type: "multi",
      options: ["Large intestine", "Mouth", "Kidney", "Skin"],
      answer: 1,
      explain: "Digestion begins in the mouth with chewing and enzymes in saliva.",
    },
    {
      id: "s4",
      skill: "chemistry",
      stage: "both",
      q: "Water freezing is an example of a…",
      type: "multi",
      options: ["chemical change", "physical change", "nuclear change", "magnetic change"],
      answer: 1,
      explain: "Freezing changes state but not the substance — physical change.",
    },
    {
      id: "s5",
      skill: "chemistry",
      stage: "both",
      q: "Which state of matter has a fixed shape and volume?",
      type: "multi",
      options: ["Gas", "Liquid", "Solid", "Plasma only"],
      answer: 2,
      explain: "Solids keep shape and volume.",
    },
    {
      id: "s6",
      skill: "chemistry",
      stage: "ks3",
      q: "The smallest particle of an element that keeps its properties is an…",
      type: "multi",
      options: ["molecule", "atom", "cell", "compound"],
      answer: 1,
      explain: "Atoms are the basic building blocks of elements.",
    },
    {
      id: "s7",
      skill: "physics",
      stage: "both",
      q: "What force pulls objects towards the Earth?",
      type: "multi",
      options: ["Friction", "Magnetism", "Gravity", "Upthrust only"],
      answer: 2,
      explain: "Gravity pulls objects towards Earth.",
    },
    {
      id: "s8",
      skill: "physics",
      stage: "both",
      q: "Sound travels as a…",
      type: "multi",
      options: ["smell", "vibration / wave", "light beam only", "static charge"],
      answer: 1,
      explain: "Sound is caused by vibrations travelling as waves.",
    },
    {
      id: "s9",
      skill: "physics",
      stage: "ks3",
      q: "Which circuit symbol represents a cell (battery unit)?",
      type: "multi",
      options: [
        "A circle only",
        "A long line and a short line",
        "A zigzag",
        "A triangle",
      ],
      answer: 1,
      explain: "A cell is drawn as a long and short parallel line.",
    },
    {
      id: "s10",
      skill: "method",
      stage: "both",
      q: "In a fair test, you should only change…",
      type: "multi",
      options: [
        "as many things as possible",
        "one variable at a time",
        "nothing at all",
        "the results after measuring",
      ],
      answer: 1,
      explain: "Change one independent variable; keep others controlled.",
    },
    {
      id: "s11",
      skill: "method",
      stage: "ks3",
      q: "A hypothesis is…",
      type: "multi",
      options: [
        "a random guess with no reason",
        "a testable prediction based on ideas",
        "the final conclusion only",
        "a type of microscope",
      ],
      answer: 1,
      explain: "A hypothesis is a testable idea about what might happen and why.",
    },
  ],
};

/** Lesson banks per skill — interactive practice sets */
const LESSONS = {
  maths: {
    number: {
      title: "Number power-up",
      blurb: "Place value, rounding and big numbers — GCSE Number foundations.",
      items: [
        {
          q: "Round 4,762 to the nearest hundred.",
          type: "typed",
          answer: "4800",
          accept: ["4800", "4,800"],
          explain: "6 tens ≥ 5, so 4,700 rounds up to 4,800.",
        },
        {
          q: "Write 3,050,000 in words (UK).",
          type: "multi",
          options: [
            "Three million and fifty thousand",
            "Three hundred and five thousand",
            "Thirty-five million",
            "Three million five hundred",
          ],
          answer: 0,
          explain: "3,050,000 = three million and fifty thousand.",
        },
        {
          q: "What is 10³?",
          type: "typed",
          answer: "1000",
          accept: ["1000", "1,000"],
          explain: "10³ = 10 × 10 × 10 = 1,000.",
        },
      ],
    },
    operations: {
      title: "Operation masters",
      blurb: "Multiply, divide and multi-step problems — accuracy for GCSE.",
      items: [
        {
          q: "Calculate 144 ÷ 12.",
          type: "typed",
          answer: "12",
          explain: "12 × 12 = 144.",
        },
        {
          q: "A shop sells 7 packs of 8 pencils. How many pencils?",
          type: "typed",
          answer: "56",
          explain: "7 × 8 = 56.",
        },
        {
          q: "What is 15²?",
          type: "typed",
          answer: "225",
          explain: "15 × 15 = 225.",
        },
      ],
    },
    fractions: {
      title: "Fractions, decimals & %",
      blurb: "The GCSE ratio & proportion toolkit starts here.",
      items: [
        {
          q: "Convert ¾ to a percentage.",
          type: "typed",
          answer: "75",
          accept: ["75", "75%"],
          explain: "¾ = 0.75 = 75%.",
        },
        {
          q: "Which is larger: 0.6 or 2/3?",
          type: "multi",
          options: ["0.6", "2/3", "They are equal"],
          answer: 1,
          explain: "2/3 ≈ 0.667 > 0.6.",
        },
        {
          q: "Find 10% of 250.",
          type: "typed",
          answer: "25",
          explain: "10% = ÷10 → 25.",
        },
      ],
    },
    algebra: {
      title: "Algebra adventure",
      blurb: "Letters for numbers — core GCSE Algebra skill.",
      items: [
        {
          q: "If y = 5, what is 3y + 1?",
          type: "typed",
          answer: "16",
          explain: "3×5 + 1 = 16.",
        },
        {
          q: "Expand: 2(x + 4)",
          type: "multi",
          options: ["2x + 4", "2x + 8", "x + 8", "2x + 6"],
          answer: 1,
          explain: "2 × x + 2 × 4 = 2x + 8.",
        },
        {
          q: "Solve: x − 7 = 12",
          type: "typed",
          answer: "19",
          explain: "x = 12 + 7 = 19.",
        },
      ],
    },
    geometry: {
      title: "Shape & measure HQ",
      blurb: "Angles, perimeter, area — GCSE Geometry foundations.",
      items: [
        {
          q: "Area of a rectangle 9 cm by 4 cm?",
          type: "typed",
          answer: "36",
          accept: ["36", "36cm2", "36 cm2", "36cm²"],
          explain: "Area = length × width = 36 cm².",
        },
        {
          q: "A straight line is…",
          type: "multi",
          options: ["90°", "180°", "270°", "360°"],
          answer: 1,
          explain: "Angles on a straight line sum to 180°.",
        },
        {
          q: "How many degrees in a full turn?",
          type: "typed",
          answer: "360",
          explain: "A full turn is 360°.",
        },
      ],
    },
    data: {
      title: "Data detectives",
      blurb: "Averages, charts and chance — GCSE Statistics start line.",
      items: [
        {
          q: "Median of 3, 9, 5?",
          type: "typed",
          answer: "5",
          explain: "Ordered: 3, 5, 9 → middle is 5.",
        },
        {
          q: "Mode of 2, 4, 4, 7, 9?",
          type: "typed",
          answer: "4",
          explain: "Mode = most frequent = 4.",
        },
        {
          q: "Probability of rolling a 6 on a fair die?",
          type: "multi",
          options: ["1/2", "1/6", "6/1", "1/3"],
          answer: 1,
          explain: "One favourable outcome out of six.",
        },
      ],
    },
  },
  english: {
    grammar: {
      title: "Grammar gym",
      blurb: "Subjects, verbs and sentence control for clear writing.",
      items: [
        {
          q: "Pick the correct verb: The team ___ winning.",
          type: "multi",
          options: ["are", "is", "be", "were is"],
          answer: 1,
          explain: "Collective noun 'team' often takes singular 'is' in formal UK English.",
        },
        {
          q: "Which is a proper noun?",
          type: "multi",
          options: ["city", "river", "London", "happiness"],
          answer: 2,
          explain: "London names a specific place.",
        },
        {
          q: "Identify the adjective: 'The fierce storm hit Wales.'",
          type: "multi",
          options: ["storm", "fierce", "hit", "Wales"],
          answer: 1,
          explain: "'Fierce' describes the storm.",
        },
      ],
    },
    punctuation: {
      title: "Punctuation patrol",
      blurb: "Apostrophes, commas and spelling — GCSE SPaG marks.",
      items: [
        {
          q: "Correct plural of 'child'?",
          type: "multi",
          options: ["childs", "childes", "children", "childrens"],
          answer: 2,
          explain: "Irregular plural: children.",
        },
        {
          q: "Which needs a comma? 'Yes I will help.'",
          type: "multi",
          options: [
            "Yes I will, help.",
            "Yes, I will help.",
            "Yes I, will help.",
            "No comma needed",
          ],
          answer: 1,
          explain: "Use a comma after a yes/no at the start.",
        },
        {
          q: "Correct spelling:",
          type: "multi",
          options: ["seperate", "separate", "seperrate", "separrate"],
          answer: 1,
          explain: "separate — there's 'a rat' in separate!",
        },
      ],
    },
    vocabulary: {
      title: "Word wizardry",
      blurb: "Meanings, synonyms and precision — stronger reading & writing.",
      items: [
        {
          q: "Antonym of 'ancient'?",
          type: "multi",
          options: ["old", "modern", "historic", "aged"],
          answer: 1,
          explain: "Modern is opposite of ancient.",
        },
        {
          q: "'Enormous' means…",
          type: "multi",
          options: ["tiny", "very large", "average", "quiet"],
          answer: 1,
          explain: "Enormous = extremely large.",
        },
        {
          q: "Best word: The scientist made a careful ___ of the results.",
          type: "multi",
          options: ["explosion", "analysis", "holiday", "rumour"],
          answer: 1,
          explain: "Analysis = detailed examination.",
        },
      ],
    },
    reading: {
      title: "Reading quests",
      blurb: "Inference, evidence and atmosphere — GCSE Reading skills.",
      items: [
        {
          passage:
            "Sam’s hands shook as he opened the envelope. Inside was a single ticket to the final. He grinned so wide his cheeks hurt.",
          q: "How does Sam feel?",
          type: "multi",
          options: ["Angry", "Bored", "Excited / happy", "Confused only"],
          answer: 2,
          explain: "Shaking hands + huge grin show excitement.",
        },
        {
          passage:
            "The village green was empty. Footballs lay abandoned. Only the flag on the hall moved in the wind.",
          q: "What does this suggest?",
          type: "multi",
          options: [
            "A lively party is starting",
            "People are elsewhere / quiet scene",
            "It is underwater",
            "It is a desert",
          ],
          answer: 1,
          explain: "Empty green and abandoned balls suggest no one is there.",
        },
        {
          q: "What is the main purpose of a non-fiction information text?",
          type: "multi",
          options: ["To invent a story", "To inform the reader", "To confuse", "To rhyme only"],
          answer: 1,
          explain: "Information texts aim to inform.",
        },
      ],
    },
    writing: {
      title: "Writing workshop",
      blurb: "Techniques and structure — GCSE Writing craft.",
      items: [
        {
          q: "Which is a metaphor?",
          type: "multi",
          options: [
            "He ran like the wind.",
            "He was a rocket down the pitch.",
            "He ran quickly.",
            "He ran and jumped.",
          ],
          answer: 1,
          explain: "Metaphor says he *was* a rocket (not like).",
        },
        {
          q: "Alliteration is…",
          type: "multi",
          options: [
            "Repeating the same starting sound",
            "A type of full stop",
            "A silent letter",
            "A rhyming couplet only",
          ],
          answer: 0,
          explain: "e.g. 'slippery snakes slid silently'.",
        },
        {
          q: "A good conclusion should…",
          type: "multi",
          options: [
            "Introduce a brand new topic only",
            "Sum up / leave a strong final idea",
            "Be longer than the whole essay always",
            "List random words",
          ],
          answer: 1,
          explain: "Conclusions wrap up and leave impact.",
        },
      ],
    },
  },
  science: {
    biology: {
      title: "Living world lab",
      blurb: "Cells, organs and ecosystems — GCSE Biology pathway.",
      items: [
        {
          q: "What do plants take in for photosynthesis?",
          type: "multi",
          options: ["Oxygen only", "Carbon dioxide and water", "Nitrogen gas only", "Soil stones"],
          answer: 1,
          explain: "CO₂ + water (+ light) → glucose + oxygen.",
        },
        {
          q: "The skeleton’s jobs include…",
          type: "multi",
          options: [
            "Digesting food only",
            "Support, protection and movement",
            "Making sound only",
            "Pumping blood only",
          ],
          answer: 1,
          explain: "Bones support, protect organs and help movement.",
        },
        {
          q: "Microorganisms that can cause disease are called…",
          type: "multi",
          options: ["nutrients", "pathogens", "minerals", "vitamins"],
          answer: 1,
          explain: "Pathogens cause disease (GCSE keyword).",
        },
      ],
    },
    chemistry: {
      title: "Materials lab",
      blurb: "States, particles and reactions — GCSE Chemistry start.",
      items: [
        {
          q: "When ice melts, particles…",
          type: "multi",
          options: [
            "Disappear",
            "Gain energy and move more freely",
            "Stop existing",
            "Turn into light",
          ],
          answer: 1,
          explain: "Heating gives particles energy to move past each other.",
        },
        {
          q: "A mixture of sand and water can be separated by…",
          type: "multi",
          options: ["Magnetism only", "Filtration", "Hearing", "Colouring in"],
          answer: 1,
          explain: "Sand is insoluble — filter it out.",
        },
        {
          q: "Rusting of iron is a…",
          type: "multi",
          options: ["physical change only", "chemical change", "change of state only", "temperature scale"],
          answer: 1,
          explain: "New substance (rust) forms — chemical change.",
        },
      ],
    },
    physics: {
      title: "Forces & energy lab",
      blurb: "Forces, electricity and waves — GCSE Physics foundations.",
      items: [
        {
          q: "Friction usually…",
          type: "multi",
          options: [
            "Speeds things up always",
            "Opposes motion between surfaces",
            "Creates gravity",
            "Only works in space",
          ],
          answer: 1,
          explain: "Friction acts against sliding motion.",
        },
        {
          q: "Which energy store is in a stretched rubber band?",
          type: "multi",
          options: ["Chemical", "Elastic potential", "Nuclear", "Gravitational only always"],
          answer: 1,
          explain: "Stretched objects store elastic potential energy.",
        },
        {
          q: "In a series circuit with one bulb removed…",
          type: "multi",
          options: [
            "Other bulbs stay on",
            "The circuit breaks and bulbs go out",
            "Voltage doubles always",
            "Nothing changes",
          ],
          answer: 1,
          explain: "Series circuits need a complete loop.",
        },
      ],
    },
    method: {
      title: "Scientist skills",
      blurb: "Variables, fair tests and data — Working Scientifically.",
      items: [
        {
          q: "The variable you measure is the…",
          type: "multi",
          options: ["control variable", "independent variable", "dependent variable", "lucky variable"],
          answer: 2,
          explain: "Dependent = what you measure (depends on the change).",
        },
        {
          q: "Repeating measurements improves…",
          type: "multi",
          options: ["handwriting only", "reliability", "the independent variable", "gravity"],
          answer: 1,
          explain: "Repeats help check reliability.",
        },
        {
          q: "A bar chart is best when data is…",
          type: "multi",
          options: [
            "categories (e.g. eye colour counts)",
            "only temperature over continuous time always",
            "secret codes",
            "never useful",
          ],
          answer: 0,
          explain: "Bar charts suit discrete/categories.",
        },
      ],
    },
  },
};

const BADGES = [
  { id: "first_steps", name: "First Steps", emoji: "👣", desc: "Complete your first diagnostic" },
  { id: "triple_test", name: "Triple Tester", emoji: "🎯", desc: "Finish diagnostics in all 3 subjects" },
  { id: "lesson_1", name: "Lesson Legend", emoji: "📖", desc: "Complete 1 personalised lesson" },
  { id: "lesson_5", name: "On a Roll", emoji: "🔥", desc: "Complete 5 lessons" },
  { id: "maths_star", name: "Maths Meteor", emoji: "☄️", desc: "Score 70%+ on Maths diagnostic" },
  { id: "english_star", name: "Word Wizard", emoji: "✨", desc: "Score 70%+ on English diagnostic" },
  { id: "science_star", name: "Lab Legend", emoji: "🧪", desc: "Score 70%+ on Science diagnostic" },
  { id: "streak_3", name: "3-Day Streak", emoji: "⚡", desc: "Learn 3 days in a row" },
  { id: "gcse_ready", name: "GCSE Pathway", emoji: "🎓", desc: "Average skill score 80%+ in a subject" },
  { id: "foundation_done", name: "Foundation Finisher", emoji: "🌱", desc: "Complete a Foundation course" },
  { id: "foundation_maths", name: "Maths Foundation", emoji: "🔢", desc: "Finish Foundation Maths" },
  { id: "foundation_english", name: "English Foundation", emoji: "📚", desc: "Finish Foundation English" },
  { id: "foundation_science", name: "Science Foundation", emoji: "🔬", desc: "Finish Foundation Science" },
  { id: "pathway_climber", name: "Pathway Climber", emoji: "🏔️", desc: "Unlock a new course stage" },
  { id: "stage_2_start", name: "Intermediate Start", emoji: "🚀", desc: "Begin Intermediate" },
  { id: "stage_3_start", name: "Secure Start", emoji: "🔷", desc: "Begin Secure stage" },
  { id: "stage_4_start", name: "GCSE Core Start", emoji: "📘", desc: "Begin GCSE Core" },
  { id: "stage_5_start", name: "Higher Start", emoji: "🎯", desc: "Begin GCSE Higher" },
  { id: "stage_6_start", name: "A* Path", emoji: "⭐", desc: "Begin A* Mastery" },
  { id: "stage_2_done", name: "Intermediate Done", emoji: "🚀", desc: "Complete Intermediate" },
  { id: "stage_3_done", name: "Secure Done", emoji: "🔷", desc: "Complete Secure stage" },
  { id: "stage_4_done", name: "GCSE Core Done", emoji: "📘", desc: "Complete GCSE Core" },
  { id: "stage_5_done", name: "Higher Done", emoji: "🎯", desc: "Complete GCSE Higher" },
  { id: "stage_6_done", name: "A* Stage Done", emoji: "⭐", desc: "Complete A* Mastery stage" },
  { id: "intermediate_maths", name: "Maths Intermediate", emoji: "🚀", desc: "Start Intermediate Maths" },
  { id: "intermediate_english", name: "English Intermediate", emoji: "🚀", desc: "Start Intermediate English" },
  { id: "intermediate_science", name: "Science Intermediate", emoji: "🚀", desc: "Start Intermediate Science" },
  { id: "intermediate_done", name: "Intermediate Hero", emoji: "🏆", desc: "Complete an Intermediate course" },
  { id: "gcse_core_maths", name: "Maths GCSE Core", emoji: "📘", desc: "Start GCSE Core Maths" },
  { id: "gcse_core_english", name: "English GCSE Core", emoji: "📘", desc: "Start GCSE Core English" },
  { id: "gcse_core_science", name: "Science GCSE Core", emoji: "📘", desc: "Start GCSE Core Science" },
  { id: "gcse_core_done", name: "GCSE Core Hero", emoji: "📘", desc: "Complete a GCSE Core course" },
  { id: "gcse_higher_maths", name: "Maths Higher", emoji: "🎯", desc: "Start Higher Maths" },
  { id: "gcse_higher_english", name: "English Higher", emoji: "🎯", desc: "Start Higher English" },
  { id: "gcse_higher_science", name: "Science Higher", emoji: "🎯", desc: "Start Higher Science" },
  { id: "gcse_higher_done", name: "Higher Hero", emoji: "🎯", desc: "Complete a Higher course" },
  { id: "astar_maths", name: "Maths A* Path", emoji: "⭐", desc: "Start A* Maths" },
  { id: "astar_english", name: "English A* Path", emoji: "⭐", desc: "Start A* English" },
  { id: "astar_science", name: "Science A* Path", emoji: "⭐", desc: "Start A* Science" },
  { id: "astar_done", name: "A* Stage Hero", emoji: "⭐", desc: "Complete an A* Mastery course" },
  { id: "astar_complete_maths", name: "Maths A*", emoji: "🥇", desc: "Finish full Maths pathway" },
  { id: "astar_complete_english", name: "English A*", emoji: "🥇", desc: "Finish full English pathway" },
  { id: "astar_complete_science", name: "Science A*", emoji: "🥇", desc: "Finish full Science pathway" },
  { id: "triple_astar", name: "Triple A*", emoji: "👑", desc: "Complete A* Mastery in all 3 subjects" },
  { id: "lesson_25", name: "Lesson Marathon", emoji: "📚", desc: "Complete 25 lessons" },
  { id: "lesson_50", name: "Century Scholar", emoji: "🦉", desc: "Complete 50 lessons" },
  { id: "exam_star", name: "Exam Ready", emoji: "📝", desc: "Score 80%+ on an exam workout" },
  { id: "exam_astar", name: "Exam Ace", emoji: "🏅", desc: "Score 90%+ on an A* workout" },
];

const ENCOURAGEMENT = [
  "Brilliant effort — mistakes are how brains grow!",
  "You're building real GCSE foundations — keep going!",
  "Super focus! Even astronauts practise the basics.",
  "Nice one! Consistency beats cramming every time.",
  "Proud of you — learning is a superpower.",
];
